


service: instagram-api-varos

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

  # Extending Lambda layer
  layers:
      - arn:aws:lambda:us-east-1:142739615414:layer:pyhton-packages-instagram:3
  # Variaveis de ambiente
  environment:
      access_token: 'EAAbdojcuBagBAOJZBAZAMkHIOCvEj8vJFgcAwfn74AN7oU3AWo2TmaiSLUgja8eO6UR0j8eYIKmq0vMSuZC22inLOwIOlCzwwvB4iQsn83ca0XudTc1HU9PUTJjFQd9vawwKoHBaJghU1sYLvsUpRL2ixWj1FnMfoQtJXPbTn0zi1MfMwZBLgJaQd5nUz1kZD'
      client_id: '1932538640467368'
      client_secret: 'fd431f0e9efb648bc6ac27fffcf4cae0'
      page_id: '527015930816521'
      instagram_account_id: '17841406234741156'
      usuario_sql: 'eduadmin'
      senha_sql: '21Varos!21'
      host_sql: 'base-edu.c2cxonpshmlt.us-east-1.rds.amazonaws.com'
      database_sql: 'edu_db'
      access_key_aws: 
      secret_key_aws: 


  iam:
    role: 
      statements:
        - Effect: Allow
          Action:
            - cloudformation:*
            - dynamodb:*
            - s3:*
          Resource: '*'

# Lambda Function definition
functions:

  #função1
  handlerconta:
    handler: handlerconta.informacoesconta
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(2 hours) #roda a funcao todo dia ás 12h
    
  #funcao2
  handlerstories:
    handler: handlerstories.informacoesstories
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(2 minutes) #roda todo dia a cada 2

  #funcao3
  handlermidias:
    handler: handlermidias.informacoesmidias
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(2 minutes) #roda a cada 2 minutos

  #funcao4
  datastudiomidias:
    handler: datastudiomidias.informacoesmidias
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(10 minutes) #roda a funcao de 4 em 4h

  #funcao5
  datastudiostories:
    handler: datastudiostories.informacoesstories
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(10 minutes)  #roda a funcao de 4 em 4h

  #funcao6
  datastudioconta:
    handler: datastudioconta.informacoesconta
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(10 minutes) #roda a funcao de 4 em 4h
  
  #funcao7
  handlerfotosmidias:
    handler: handlerfotosmidias.handleruploadfotosmidias
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(10 minutes) #roda a funcao todo dia as 08:00 horas

  #funcao8
  handlerfotosstories:
    handler: handlerfotosstories.handleruploadfotosstories
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(10 minutes) #roda a funcao todo dia as 08:00 horas























