
service: instagram-api-varos

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

  # Extending Lambda layer
  layers:
      - arn:aws:lambda:us-east-1:142739615414:layer:pyhton-packages-instagram:3
  # Variaveis de ambiente
  environment:
      access_token: 'EAAbdojcuBagBAGXZAIqMHZAMQE7vE8wuOtNQPloCGRuArc7ZAAdcZBo18nhVmhau6wfiOemklhrZCqMSp6LL1dx2oJ8HhgroE5TMaAjuPFgQgW9AjaOeEPq1nGCB1cZAZBCqlKUAp90dshL67UBI8gFj40cVuTk7wa7LNAjQj10WglPkXXdt4gBuLtqanJ1ntMZD'
      client_id: '1932538640467368'
      client_secret: 'fd431f0e9efb648bc6ac27fffcf4cae0'
      page_id: '527015930816521'
      instagram_account_id: '17841406234741156'
      usuario_sql: 'eduadmin'
      senha_sql: '21Varos!21'
      host_sql: 'base-edu.c2cxonpshmlt.us-east-1.rds.amazonaws.com'
      database_sql: 'edu_db'


  iam:
    role: 
      statements:
        - Effect: Allow
          Action:
            - cloudformation:*
            - dynamodb:*
            - s3:*
          Resource: '*'

# Lambda Function definition
functions:

  #função1
  handlerconta:
    handler: handlerconta.informacoesconta
    timeout: 50 #tempo de duração da função
    events:
      - schedule: cron(0 12 * * ? *) #roda a funcao todo dia ás 12h
    
  #funcao2
  handlerstories:
    handler: handlerstories.informacoesstories
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(2 minutes) #roda todo dia a cada 2

  #funcao3
  handlermidias:
    handler: handlermidias.informacoesmidias
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(25 minutes) #roda a cada 2 minutos

  #funcao4
  datastudiomidias:
    handler: datastudiomidias.informacoesmidias
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(4 hours) #roda a funcao de 4 em 4h

  #funcao5
  datastudiostories:
    handler: datastudiostories.informacoesstories
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(4 hours)  #roda a funcao de 4 em 4h

  #funcao6
  datastudioconta:
    handler: datastudioconta.informacoesconta
    timeout: 50 #tempo de duração da função
    events:
      - schedule: rate(4 hours) #roda a funcao de 4 em 4h
  
  #funcao7
  handlerfotosmidias:
    handler: handlerfotosmidias.handleruploadfotosmidias
    timeout: 50 #tempo de duração da função
    events:
      - schedule: cron(0 8 * * ? *) #roda a funcao todo dia as 08:00 horas

  #funcao8
  handlerfotosstories:
    handler: handlerfotosstories.handleruploadfotosstories
    timeout: 50 #tempo de duração da função
    events:
      - schedule: cron(0 8 * * ? *) #roda a funcao todo dia as 08:00 horas























