

service: instagramApiLambdaFunction

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

  # Extending Lambda layer
  layers:
      - arn:aws:lambda:us-east-1:142739615414:layer:python-package-instagramapi:2
  # Variaveis de ambiente
  environment:
      access_token: 'EAAbdojcuBagBALIE0bL5Afr0QOMIlqG0zc0GK3nntHUB9FeBgH8PetFSZAZBSZCZBIYp6LQErfn8ywzlsZBN9gW1jSaZCzCejcQmGin8LXNBc9FQ65oxHidMHR54m131hD0MeQ9cGwdedpX1YpVuk1X2jC23QafMZBFmSjJXMKH0wYZCDk7XDtMsWsWGbK6dvQwZD'
      client_id: '1932538640467368'
      client_secret: 'fd431f0e9efb648bc6ac27fffcf4cae0'
      page_id: '527015930816521'
      instagram_account_id: '17841406234741156'
  iam:
    role: 
      statements:
        - Effect: Allow
          Action:
            - cloudformation:*
            - dynamodb:*
            - s3:*
          Resource: '*'

# Lambda Function definition
functions:

  #função1
  handlerconta:
    handler: handlerconta.informacoesconta
    events:
      - schedule: cron(0 12 * * ? *) #roda a funcao todo dia ás 12h
    
  #funcao2
  handlerstorie:
    handler: handlerstorie.informacoesstorie
    events:
      - schedule: rate(2 minutes) #roda todo dia a cada 2

  #funcao3
  handlermidia:
    handler: handlermidia.informacoesmidia
    events:
      - schedule: rate(25 minutes) #roda a cada 2 minutos

  #funcao4
  datastudiomidias:
    handler: datastudiomidias.informacoesmidias

  #funcao5
  datastudiostories:
    handler: datastudiostories.informacoesstories

  #funcao6
  datastudioconta:
    handler: datastudioconta.informacoesconta


resources:
  Resources:
    uploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: instagram-api-bucket






















